language: python
python:
  - "3.6"
install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -r reqs/test-requirements.txt
script: "py.test --cov=modules tests/"
after_success:
  coveralls
env:
  - USE_DICT_DB=1
